sudo: false

language: python

cache:
  directories:
    - ~/.cache/pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran

before_install:
  - pip install pip setuptools --upgrade

install:
  - pip install -e .[dev]

script: 
  - py.test tests --cov fio_buffer --cov-report term-missing

after_success:
  - coveralls
